config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'welcome#index'
  resources :blogs do
    resources :posts
  end
  namespace :account do
    resources :blogs do
      resources :posts
    end
  end
end

app/models/blog.rb
class Blog < ApplicationRecord
  validates :title, presence: true
  belongs_to :user
  has_many :posts, :dependent => :destroy
end

app/controllers/account/blogs_controller.rb
class Account::BlogsController < ApplicationController
  def index
    @blogs = current_user.blogs
  end
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :authenticate_user! , except: [:show]
  before_action :find_blog_and_check_permission, only: [:edit, :update, :destroy]

  def new
    @blog = Blog.new
  end

  def create
    @blog = Blog.new(blog_params)
    @blog.user = current_user
    if @blog.save
      redirect_to account_blogs_path
    else
      render :new
    end
  end

  def show
    @blog = Blog.find(params[:id])
    @posts = @blog.posts.recent.paginate(:page => params[:page], :per_page => 5)
  end

  def edit
  end

  def update
    if @blog.update(blog_params)
      redirect_to account_blogs_path, notice: "Update Success"
    else
      render :edit
    end
  end

  def destroy
    @group.destroy
    flash[:alert] = "Group deleted"
    redirect_to account_blogs_path
  end

  private

  def find_blog_and_check_permission
    @blog = Blog.find(params[:id])
    if current_user != @blog.user
      redirect_to root_path, alert: "You have no permission."
    end
  end

  def blog_params
    params.require(:blog).permit(:title, :description)
  end

end

app/helpers/account/blogs_helper.rb
module Account::BlogsHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/views/blogs/edit.html.erb
<div class="container">
  <h1>Edit blog</h1>
  <%= simple_form_for @blog do |f| %>
    <%= f.input :title, hint: '20 characters', placeholder: "name your blog", input_html: { maxlength: 20 } %>
    <%= f.input :description, hint: '50 characters', placeholder: "describe your blog", input_html: { maxlength: 50 } %>
    <%= f.submit "Submit", class: "btn btn-default btn-sm" %>
  <% end %>
</div>

app/views/blogs/index.html.erb
<% @posts.each do |post| %>
  <div class="container" style="background-color: #ffffff; padding: 20px 50px 50px 50px">
    <h1><%= link_to(post.title, account_post_path(post)) %></h1>
    <p><%= post.created_at.strftime("%B %d, %Y %R") %></p>
    <p><%= markdown(post.article) %></p>
  </div>
  <div style="padding-bottom: 50px"></div>
<% end %>
<!-- <div align="center" style="margin: auto"><%#= will_paginate @posts %></div> -->

app/views/blogs/new.html.erb
<div class="container">
  <h1>New blog</h1>
  <%= simple_form_for @blog do |f| %>
    <%= f.input :title, hint: '20 characters', placeholder: "name your blog", input_html: { maxlength: 20 } %>
    <%= f.input :description, hint: '50 characters', placeholder: "describe your blog", input_html: { maxlength: 50 } %>
    <%= f.submit "Submit", class: "btn btn-default btn-sm" %>
  <% end %>
</div>

app/views/blogs/show.html.erb
<% @posts.each do |post| %>
  <div class="container" style="background-color: #ffffff; padding: 20px 50px 50px 50px">
    <h1><%= link_to(post.title, account_post_path(post)) %></h1>
    <p><%= post.created_at.strftime("%B %d, %Y %R") %></p>
    <p><%= markdown(post.article) %></p>
  </div>
  <div style="padding-bottom: 50px"></div>
<% end %>
<!-- <div align="center" style="margin: auto"><%#= will_paginate @posts %></div> -->