config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'welcome#index'
  resources :blogs do
    resources :posts
  end
  namespace :account do
    resources :blogs do
      resources :posts
    end
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  belongs_to :blog
  validates :title, presence: true
  validates :article, presence: true
  scope :recent, -> {order("created_at DESC")}
end

app/controllers/account/posts_controller.rb
class Account::PostsController < ApplicationController
  before_action :authenticate_user!
  def index
    @posts = current_user.posts.recent
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    before_action :authenticate_user!, except: [:index, :show]
    before_action :find_post_and_check_permission, only: [:edit, :update, :destroy]

    def index
      @blog = Blog.find(params[:blog_id])
      @posts = @blog.posts.all.recent
    end

    def new
      @blog = Blog.find(params[:blog_id])
      if current_user != @blog.user
        redirect_to root_path, alert: "You have no permission."
      else
        @post = Post.new
      end
    end

    def create
      @blog = Blog.find(params[:blog_id])
      @post = Post.new(post_params)
      @post.blog = @blog
      @post.user = current_user

      if @post.save
        redirect_to blog_posts_path(@blog)
      else
        render :new
      end
    end

    def show
      @blog = Blog.find(params[:blog_id])
      @post = Post.find(params[:id])
    end

    def edit
    end

    def update
      if @post.update(post_params)
        redirect_to blog_posts_path(@blog), notice: "Update Success"
      else
        render :edit
      end
    end

    def destroy
      @post.destroy
      flash[:alert] = "Post deleted"
      redirect_to blog_posts_path(@blog)
    end

    private

    def find_post_and_check_permission
      @blog = Blog.find(params[:blog_id])
      @post = Post.find(params[:id])
      if current_user != @post.user
        redirect_to root_path, alert: "You have no permission."
      end
    end


    def post_params
      params.require(:post).permit(:title, :article)
    end
end

app/helpers/account/posts_helper.rb
module Account::PostsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
  class CodeRayify < Redcarpet::Render::HTML
    def block_code(code, language)
      CodeRay.scan(code, language).div
    end
  end

  def markdown(text)
    coderayified = CodeRayify.new(:filter_html => true,
                                  :hard_wrap => true)
    options = {
      :fenced_code_blocks => true,
      :no_intra_emphasis => true,
      :autolink => true,
      :lax_html_blocks => true,
    }
    markdown_to_html = Redcarpet::Markdown.new(coderayified, options)
    markdown_to_html.render(text).html_safe
  end
end

app/views/posts/edit.html.erb
<div class="container">
  <h1>Editing</h1>
  <%= simple_form_for [@blog, @post] do |f| %>
    <%= f.input :title %>
    <%= f.input :article, :input_html => {:style => 'height: 700px'}%>
    <%= f.submit "Submit", class: "btn btn-default btn-sm" %>
  <% end %>
</div>

app/views/posts/index.html.erb
<div class="container">
  <% if current_user && current_user == @blog.user %>
    <%= link_to('New post', new_blog_post_path, class: "btn btn-default") %>
  <% end %>
</div>
<% @posts.each do |post| %>
  <div class="container" style="background-color: #ffffff; padding: 20px 50px 50px 50px">
    <h1><%= link_to(post.title, blog_post_path(@blog, post)) %></h1>
    <p><%= post.created_at.strftime("%B %d, %Y %R") %></p>
    <p><%= markdown(post.article) %></p>
  </div>
  <div style="padding-bottom: 50px"></div>
<% end %>
<div align="center" style="margin: auto"><%#= will_paginate @posts %></div>

app/views/posts/new.html.erb
<div class="container">
  <h1>Writing</h1>
  <%= simple_form_for [@blog, @post] do |f| %>
    <%= f.input :title %>
    <%= f.input :article, :input_html => {:style => 'height: 700px'}%>
    <%= f.submit "Submit", class: "btn btn-default btn-sm" %>
  <% end %>
</div>

app/views/posts/show.html.erb
<div class="container" style="background-color: #ffffff; padding: 20px 50px 50px 50px">
  <div style="inline">
    <% if current_user && current_user == @post.user %>
      <%= link_to('Edit article', edit_blog_post_path(@blog, @post), class: "btn btn-default pull-right") %>
    <% end %>
    <h1><%= @post.title %></h1>
  </div>
  <p><%= markdown(@post.article) %></p>
</div>